// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['application']['FileApp']['Close'](arg1);
}

export function DeletefileByPath(arg1) {
  return window['go']['application']['FileApp']['DeletefileByPath'](arg1);
}

export function GetAllDir() {
  return window['go']['application']['FileApp']['GetAllDir']();
}

export function GetByRootpath(arg1) {
  return window['go']['application']['FileApp']['GetByRootpath'](arg1);
}

export function GetByRootpaths() {
  return window['go']['application']['FileApp']['GetByRootpaths']();
}

export function OpenDirectoryDialog() {
  return window['go']['application']['FileApp']['OpenDirectoryDialog']();
}

export function OpenfileByPath(arg1) {
  return window['go']['application']['FileApp']['OpenfileByPath'](arg1);
}

export function RemoveAll2Trash(arg1) {
  return window['go']['application']['FileApp']['RemoveAll2Trash'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['application']['FileApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['application']['FileApp']['Startup'](arg1);
}
