// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDir() {
  return window['go']['application']['FileApp']['GetAllDir']();
}

export function GetByRootpath(arg1) {
  return window['go']['application']['FileApp']['GetByRootpath'](arg1);
}

export function Startup(arg1) {
  return window['go']['application']['FileApp']['Startup'](arg1);
}
