// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileutil} from '../models';
import {application} from '../models';
import {context} from '../models';

export function DeletefileByPath(arg1:string):Promise<void>;

export function GetAllDir():Promise<Array<fileutil.Dir>>;

export function GetByRootpath(arg1:string):Promise<Array<fileutil.Dir>>;

export function GetByRootpaths():Promise<Array<application.RootpathInfo>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenfileByPath(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
